# .golangci.yml
# Path: .golangci.yml
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - dupl
    - gosec
    - nilerr
    - nilnesserr
    - nilnil
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - wrapcheck
    - errcheck
    - gocritic
    - govet

  settings:
    dupl:
      threshold: 150
    errcheck:
      exclude-functions:
        - io/ioutil.ReadAll
        - io.Copy
        - io.WriteString
        - os.Stdout.Write
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - paramTypeCombine
    revive:
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        - name: argument-limit
          arguments: [6]
        - name: cognitive-complexity
          arguments: [12]
        - name: cyclomatic
          arguments: [12]
        - name: unhandled-error
          arguments: []
        - name: bool-literal-in-expr
        - name: comment-spacings
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: early-return
        - name: empty-block
        - name: error-return
        - name: error-strings
        - name: errorf

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
